name: Build LaTeX PDF

on:
  push:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f Dockerfile -t compile-latex .

      - name: Build PDF
        run: |
          docker run --rm -i -v "$PWD":/data compile-latex pdflatex ./Iurev_Frontend_CV.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Iurev_Frontend_CV.pdf
          path: Iurev_Frontend_CV.pdf

      - name: Create release
        run: |
          gh release upload ${{github.event.release.tag_name}} Iurev_Frontend_CV.pdf